### ISSUE TITLE
failing on valid patterns

### ISSUE THREAD

**Issue by radiovisual** [johnhenry/valid-email#1]
I took some valid email address [from Wikipedia](https://en.wikipedia.org/wiki/Email_address), and I found that the valid-email module is not validating these valid patterns:

<pre>
"very.unusual.@.unusual.com"@example.com
"very.(),:;<>[]".VERY."very@\\ "very".unusual"@strange.example.com'
"()<>[]:,;@\\"!#$%&\'*+-/=?^_`{}| ~.a"@example.org
user@[IPv6:2001:db8::1]
</pre>

Also, normally `..` before `@` is invalid, but gmail allows it, so this address is **valid**:
`john..doe@gmail.com`

While this email is **invalid**:
`john..doe@example.com`

**Comment by radiovisual** [comment]
I have [created a fork of this project](https://github.com/radiovisual/valid-email), which adds [unit tests to highlight the problem](https://github.com/radiovisual/valid-email/blob/master/test.js#L13).

**Comment by johnhenry** [comment]
@radiovisual thanks for pointing this out and sorry for the late response. I made this as somewhat of an academic project years ago and hadn't even realized that others were using it. I've added a note on the accuracy, but I'm going to close this issue as I don't think that it's really worth fixing. If someone were to submit a pull request, I'd be more than happy to review it.

**Comment by davisjam** [comment]
I incorporated these tests into #5. Nice job @radiovisual.
