### ISSUE TITLE
npm package publish lib missing

### ISSUE THREAD

**Issue by crobinson42** [johnhenry/valid-email#8]
not publishing ./lib/valid-email.js in npm package...

**Comment by johnhenry** [comment]
I'm sorry, @crobinson42, I don't understand what you mean? Could you please be more explicit?

**Comment by crobinson42** [comment]
@johnhenry `index.js` requires lib/ but `lib/` does not exist in `node_modules/valid-email` when this package is installed on npm.

This is a bug fix.
